title: DevianceNet
description: This is a GitHub Pages for DevianceNet.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
github:
  zip_url: https://drive.google.com/drive/u/2/folders/1nAWZD0dGXM3CjhwrN9iyVxo4g6L8rPhg